# Set the default terminal to screen-256color
set -g default-terminal "screen-256color"

# Set the prefix key to Control-a and unbind Control-b
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Unbind % and bind | to split the window horizontally
unbind %
bind | split-window -h

# Unbind '"' and bind - to split the window vertically
unbind '"'
bind - split-window -v

# Unbind r and bind r to reload the tmux configuration
unbind r
bind r source-file ~/.tmux.conf

# Bind keys for resizing panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Bind -r m to toggle pane zooming
bind -r m resize-pane -Z

# Enable mouse support
set -g mouse on

# Set window mode keys to vi
set-window-option -g mode-keys vi

# Bind keys for copy mode in vi-style
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Unbind MouseDragEnd1Pane in copy mode
unbind -T copy-mode-vi MouseDragEnd1Pane

# Remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Configure TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'

# List of TMUX plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # Automatically save sessions every 15 minutes

# Set the theme
set -g @themepack 'powerline/default/cyan'

# Configure session and pane restoration
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
